# Generated by Django 5.0.4 on 2024-05-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('stock_status', models.BooleanField(default=False)),
                ('news1_status', models.BooleanField(default=False)),
                ('news2_status', models.BooleanField(default=False)),
                ('model_training_status', models.BooleanField(default=False)),
                ('mse', models.FloatField(blank=True, null=True)),
                ('r2_score', models.FloatField(blank=True, null=True)),
                ('day1', models.FloatField(blank=True, null=True)),
                ('day2', models.FloatField(blank=True, null=True)),
                ('day3', models.FloatField(blank=True, null=True)),
                ('day4', models.FloatField(blank=True, null=True)),
                ('day5', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
