# Generated by Django 5.0.4 on 2024-05-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashBoard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processlog',
            old_name='news1_status',
            new_name='bs_status',
        ),
        migrations.RenameField(
            model_name='processlog',
            old_name='news2_status',
            new_name='toi_status',
        ),
    ]
